### ISSUE TITLE
#Bug

### ISSUE THREAD

**Issue by moderGamer** [sterlp/svg2png#17]
Hello im Using Your Library in Android project 
me using in code 
```java

list.add("-f".concat(input.getText().toString().trim()));
list.add("-n".concat(output.getText().toString().trim()));
try {
				org.sterl.svg2png.Main.main(list.toArray(new String[0]));
		} catch (Exception e) {
				e.printStackTrace();
		}
```

result === 
![Screenshot_20230301-002750_MT Manager](https://user-images.githubusercontent.com/125615066/221978258-e945caec-bb06-4b1c-a443-ff9aa10328c3.jpg)

not Convert Bro plz Help me to Run in Your Library to Android And dont Close Issues
tnks
[Moder Gamer]

**Comment by sterlp** [comment]
Hello @moderGamer 
thanks for the issue, the problem is the underlining lib which requires the Java 2D Api to be present. The Java version on android is missing this, see also:

see also issue: https://github.com/sterlp/svg2png/issues/12
https://stackoverflow.com/questions/7418937/how-to-integrate-batik-with-android-to-open-display-svg-files

Hope this links help. I haven't found a good alternative to batik as so android isn't supported.

Sorry for that.

**Comment by moderGamer** [comment]
> Hello @moderGamer thanks for the issue, the problem is the underlining lib which requires the Java 2D Api to be present. The Java version on android is missing this, see also:
> 
> see also issue: #12 https://stackoverflow.com/questions/7418937/how-to-integrate-batik-with-android-to-open-display-svg-files
> 
> Hope this links help. I haven't found a good alternative to batik as so android isn't supported.
> 
> Sorry for that.

Hello @sterlp 
you can get help from the Android Svg library to access the Api, I think it is a good option, thanks for your answer.
